# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Software Design Rules
description: > # this means to ignore newlines until "baseurl:"
  Design rules for effective development.
baseurl: "/software-design-rules" # the subpath of your site, e.g. /blog
url: "https://jlapolla.github.io" # the base hostname & protocol for your site
github_username: jlapolla
github_project: software-design-rules

# Build settings
markdown: kramdown

collections:
  code_samples:
    output: true
  rules:
    output: true
  my_tags:
    output: true

defaults:
  -
    scope:
      path: ""
      type: code_samples
    values:
      layout: "code-sample"
      permalink: /code-samples/:path/
      excerpt_separator: \{% endhighlight %\}
  -
    scope:
      path: ""
      type: rules
    values:
      layout: "rule"
      permalink: /:collection/:path/
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: "tag"
      permalink: /tags/:path/
